#!/bin/bash
# Global emerge interceptor for ZFS snapshots

# Only root can do actions that require snapshotting
# Only root can do snapshots
# So we don't need this as non root. Saves us trouble
if [[ $EUID -eq 0 ]]; then
    echo "emerge $*" > /var/tmp/.emerge_cmd_metadata
fi

exec /usr/bin/emerge "$@"
